[package]
name = "swb"
version = "1.2.0"
description = "Sliding window buffer with random access"
repository = "https://github.com/research-ag/swb"
keywords = [ "buffer", "sliding", "window", "queue" ]
license = "Apache-2.0"

[dependencies]
core = "2.0.0"

[dev-dependencies]
test = "2.1.1"

[toolchain]
wasmtime = "40.0.0"
moc = "1.0.0"
