[package]
name = "swb"
version = "1.2.3"
description = "Sliding window buffer with random access"
repository = "https://github.com/research-ag/swb"
keywords = [ "buffer", "sliding", "window", "queue" ]
license = "Apache-2.0"

[dependencies]
core = "2.5.0"

[requirements]
moc = "1.0.0"

[toolchain]
moc = "1.7.0"
